version: '3'

services:
  product-api:
    build:
      context: .
    container_name: product-api
    image: gustavofranca/simple-ecommerce-product-api
    networks:
      - mysql-net
    environment:
      - DATABASE_USER=simple-eccomerce
      - DATABASE_PASSWORD=simple-eccomerce
      - DATABASE_ADDRESS=tcp(mysql:3306)
      - DATABASE_NAME=product
      - PORT=9000
      - TRACER_HOST=host.docker.internal
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    entrypoint: dockerize -timeout 250s -wait tcp://mysql:3306 /app/cmd/api/main
    restart: always

  mysql:
    container_name: mysql
    image: mysql
    networks:
      - mysql-net
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=product
      - MYSQL_USER=simple-eccomerce
      - MYSQL_PASSWORD=simple-eccomerce
      - MYSQL_ROOT_PASSWORD=simple-eccomerce
      - LANG=C.UTF-8
    ports:
      - 3306:3306
    command: [ "mysqld","--default-authentication-plugin=mysql_native_password" ]
networks:
  mysql-net: { }
